# Generated by Django 3.2.16 on 2022-12-31 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mo_blogs',
            name='description',
            field=models.TextField(),
        ),
    ]
